#!/usr/bin/env bash

set -e # exit if something fails

export BUILD_DIR="${BUILD_DIR:-xAuto}"
export SIDEKICK_ROOT=$(pwd)
cd ../../.. || exit
readonly _OBS_ROOT=$(pwd)
export OBS_ROOT=${_OBS_ROOT}
export BUILD_ROOT="${OBS_ROOT}/${BUILD_DIR}"
cd "${SIDEKICK_ROOT}"

readonly cyn=$'\e[1;36m'
readonly bold=$'\e[1m'
readonly reset=$'\e[0m'

main() {
  sudo echo "${cyn}Deploying Sidekick${reset}"
  cd "${BUILD_ROOT}" || exit
  make || exit
  cd "${SIDEKICK_ROOT}"
  ./package dev || exit
  if [ -f "${BUILD_ROOT}/Sidekick.pkg" ]; then
    sudo installer -pkg "${BUILD_ROOT}/Sidekick.pkg" -target /
  fi
}

main "$@"