#!/bin/bash

set -e # exit if something fails

BUILD_DIR="${BUILD_DIR:-xAuto}"
SIDEKICK_ROOT="$(pwd)"
cd ../../.. || exit
OBS_ROOT="$(pwd)"
BUILD_ROOT="${OBS_ROOT}/${BUILD_DIR}"
cd "${SIDEKICK_ROOT}"

cyn=$'\e[1;36m'
bold=$'\e[1m'
reset=$'\e[0m'

main() {
  sudo echo "${cyn}Deploying Sidekick${reset}"
  cd "${BUILD_ROOT}" || exit
  make || exit
  cd "${SIDEKICK_ROOT}"
  ./package dev || exit
  if [ -f "${BUILD_ROOT}/Sidekick.pkg" ]; then
    sudo installer -pkg "${BUILD_ROOT}/Sidekick.pkg" -target /
  fi
}

main "$@"
